### ISSUE TITLE
[FEATURE] Support set authentication configurations to connect to a Pulsar cluster

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/pulsar-spark#45]
**Is your feature request related to a problem? Please describe.**
Able to configuring authentication for the spark connector

**Comment by atezs82** [comment]
@syhily The lack of authentication is causing problems when we want to use the connector. Would you mind if I would push up a feature improvement for this?

My ideas on this are the following:
- we can leverage the already existing parameters for client connection as well (this is from `PulsarOptions.scala`): 
```scala
  val AUTH_PLUGIN_CLASS_NAME = "authpluginclassname"
  val AUTH_PARAMS = "authparams"
  val TLS_TRUST_CERTS_FILE_PATH = "tlstrustcertsfilepath"
  val TLS_ALLOW_INSECURE_CONNECTION = "tlsallowinsecureconnection"
  val USE_TLS = "usetls"
  val TLS_HOSTNAME_VERIFICATION_ENABLE = "tlshostnameverificationenable"
```
- Change `CachedPulsarClient::createPulsarClient` and `PulsarMetadataReader::fetchOffsetForTopic` accordingly to configure and create a Pulsar Client for authentication (using the parameters above). Based on the code it does not seem to be the case, but are there further changes needed in other parts of the code?
- We are using Pulsar with different credentials for the admin and the client endpoints. Since we have `service.url` and `admin.url` already as parameters, we can have `service.authpluginclassname`, `service.authparams`, `service.tlstructcertsfilepath` and so on as well for the service. Changing the admin authentication parameters in this fashion (eg. to have `admin.authpluginclassname`, `admin.authparams`, `admin.tlstrustscertfilepath`) unfortunately would break backwards compatibility (although these parameters are currently missing from the `README.md` of the connector), but I would also allow users to use this changed form as well for admin credentials. What do you think about this?

If you do not mind, I will push a PR on this once I finished local testing.

**Comment by atezs82** [comment]
Please see the PR above on my proposed solution to this (it became a little bit different that what I wrote above).

**Comment by syhily** [comment]
> If you do not mind, I will push a PR on this once I finished local testing.
> 
> _ADDITION:_ During testing I have seen that since `PulsarConfigUpdater` has some not implemented parts, and the `pulsar.client` prefix is needed for the authentication parameters. I'll take these into account in the PR.

Yeah, using existing params is simple with a little modification, I have done the same job like you but suck with the intergration test (Cause I have bumped all the dependencies). Anyway, your PR is perfect.
